# Remote theme directory
remote_theme:  analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Nishant Rai
description: "Hi, I’m Nishant Rai, an aspiring Data Scientist with a Master’s degree in Chemistry. My analytical mindset, honed through years of solving complex scientific problems, now drives my passion for Data Science and Machine Learning. I focus on applying statistical analysis and data-driven solutions to tackle real-world business challenges and deliver measurable impact. In my portfolio, you’ll find projects that showcase my ability to use data science techniques to generate actionable insights, optimize processes, and support decision-making in dynamic environments. I’m dedicated to continuous learning and staying on top of the latest trends in the field.
Feel free to explore my work on GitHub and LinkedIn, or download my resume from the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
avatar_image: /img/

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Coventry, UK"
resume_url: /docs/DSI resume FINAL 3.pdf
#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/nishant-rai-81a993329//#" # Add your linkedln handle
github: "https://github.com/NishantRai567/#"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

